language: php

php:
    - 7.0
    - 7.1
    - 7.2

sudo: false

install:
    - composer install --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
        - 529265776@qq.com
    on_success: change
    on_failure: always

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - travis_retry php vendor/bin/coveralls -v