language: php

php:
    - 7.0
    - 7.1
    - 7.2

sudo: false

install:
    - composer install --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - 529265776@qq.com
    on_success: change
    on_failure: always

script: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text